// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Orange.Services.ProductAPI.DbContexts;

#nullable disable

namespace Orange.Services.ProductAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231130175340_seedProduct")]
    partial class seedProduct
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Orange.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "Appetizer",
                            Description = "roin posuere sollicitudin odio, quis malesuada metus ornare et. Morbi quis gravida eros. Vivamus aliquam iaculis lorem, gravida lobortis est mollis sit amet. Donec ut sapien a neque luctus feugiat in at orci. Cras odio massa, elementum vitae euismod vitae, dapibus et quam. Pellentesque ex arcu, ornare non libero sed, vestibulum vehicula tortor.",
                            ImageUrl = "https://orangemicroservice.blob.core.windows.net/menu/samoosa.jpg",
                            Name = "Samosa",
                            Price = 15.0
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryName = "Appetizer",
                            Description = "roin posuere sollicitudin odio, quis malesuada metus ornare et. Morbi quis gravida eros. Vivamus aliquam iaculis lorem, gravida lobortis est mollis sit amet. Donec ut sapien a neque luctus feugiat in at orci. Cras odio massa, elementum vitae euismod vitae, dapibus et quam. Pellentesque ex arcu, ornare non libero sed, vestibulum vehicula tortor.",
                            ImageUrl = "https://orangemicroservice.blob.core.windows.net/menu/paneer.jpg",
                            Name = "Paneer Tikka",
                            Price = 13.99
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "Desert",
                            Description = "roin posuere sollicitudin odio, quis malesuada metus ornare et. Morbi quis gravida eros. Vivamus aliquam iaculis lorem, gravida lobortis est mollis sit amet. Donec ut sapien a neque luctus feugiat in at orci. Cras odio massa, elementum vitae euismod vitae, dapibus et quam. Pellentesque ex arcu, ornare non libero sed, vestibulum vehicula tortor.",
                            ImageUrl = "https://orangemicroservice.blob.core.windows.net/menu/sweet%20pie.jpg",
                            Name = "Sweet Pie",
                            Price = 13.99
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryName = "Entree",
                            Description = "roin posuere sollicitudin odio, quis malesuada metus ornare et. Morbi quis gravida eros. Vivamus aliquam iaculis lorem, gravida lobortis est mollis sit amet. Donec ut sapien a neque luctus feugiat in at orci. Cras odio massa, elementum vitae euismod vitae, dapibus et quam. Pellentesque ex arcu, ornare non libero sed, vestibulum vehicula tortor.",
                            ImageUrl = "https://orangemicroservice.blob.core.windows.net/menu/pavbaji.jpg",
                            Name = "Pav Bhaji",
                            Price = 15.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
